### ISSUE TITLE
Imputar desemprego

### ISSUE THREAD

**Issue by gabrielfdm** [gabrielfdm/ferranaData#2]
Imputar desemprego em ferranaTrans a partir de planilha do WhatsApp.

**Comment by mateuspestana** [comment]
De onde tiramos o Desemprego? Não está na planilha do IPEA. Até tem lá, mas é uma outra metodologia (e aí os dados são distintos).

**Comment by gabrielfdm** [comment]
Desemprego aqui: https://ww2.ibge.gov.br/home/estatistica/indicadores/trabalhoerendimento/pme/default.shtm
