### ISSUE TITLE
Criar gráfico com evolução das cadeiras

### ISSUE THREAD

**Issue by gabrielfdm** [gabrielfdm/ferranaData#3]

**Comment by mateuspestana** [comment]
As eleições de 1947 foram suplementares. Quando crio o gráfico, por obviedade, ele joga como uma nova eleição, ao invés de complementar com a de 1945. **Excluímos ou somamos a 45?** No caso de somar, como é? Pois isso dá uma alteração absurda no resultado, como se em 47 o número de cadeiras total tivesse diminuído absurdamente. Aí todos os partidos tem uma queda de 45 pra 47 e de 47 pra 50 o número volta a ser normal. 

PS: Estou com **problema de _codificação_**, por isso não adicionarei a imagem do gráfico aqui. Mas o código já está lá (vou adicionar outros gráficos ainda). O ideal é tentar executar do seu para acertar a codificação. Aqui, está sumindo o ç, º, ~, â, etc.

**Comment by gabrielfdm** [comment]
Você tentou abrir pelo Rstudio o script com a codificação correta (UTF-8)? File -> Reopen w/ encoding. De qualquer forma, não sei como proceder com relação à soma das eleições. Que tal pular direto para 1950. Isso também corrigiria o problema da falta de dados do modelo estrutural para a década de 1940 (que não teve copa :p)

**Comment by mateuspestana** [comment]
Acho que começar em 50 é melhor! Mas to vendo também que a variável WC, sadly, é furada...

Atenciosamente,

Matheus Pestana
Mestrando em Ciência Política
IESP/UERJ
Em 5 de out de 2018 15:52 -0300, Gabriel Melo <notifications@github.com> escreveu:
> Você tentou abrir pelo Rstudio o script com a codificação correta (UTF-8)? File -> Reopen w/ encoding. De qualquer forma, não sei como proceder com relação à soma das eleições. Que tal pular direto para 1950. Isso também corrigiria o problema da falta de dados do modelo estrutural para a década de 1940 (que não teve copa :p)
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
-Enviado pelo email IESP by Google.
